services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'mydatabase'
    volumes:
      - ticketmaster-db-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'

  nginx:
    build:
      context: .
      dockerfile: dockerfile_nginx
    ports:
      - "8080:80"
    networks:
      - app-network

  backend1:
    build:
      context: .
    networks:
      - app-network
  
  backend2:
    build:
      context: .
    networks:
      - app-network

volumes:
  ticketmaster-db-data:

networks:
  app-network:
    driver: bridge